name: Deploy to Firebase Hosting on merge
on:
  push:
    branches:
      - develop
    paths:
      - 'frontend/**'
      - '.github/workflows/firebase-hosting-merge.yml'

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup working directory
        run: cd frontend

      - name: Install dependencies
        run: npm install
        working-directory: frontend

      - name: Build
        run: npm run build
        working-directory: frontend

      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_TRAVEL_PLANNER_335A8 }}
          channelId: live
          projectId: travel-planner-335a8
          entryPoint: frontend
