name: Deploy Backend to Cloud Run

on:
  push:
    branches:
      - develop
    paths:
      - 'backend/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.TRAVEL_PLANNER_335A8 }}

      - name: Deploy to Cloud Run
        run: |
          gcloud builds submit backend \
            --tag gcr.io/${{ secrets.TRAVEL_PLANNER_335A8 }}/travel-backend

          gcloud run deploy travel-backend \
            --image gcr.io/${{ secrets.TRAVEL_PLANNER_335A8 }}/travel-backend \
            --platform managed \
            --region asia-east1 \
            --allow-unauthenticated
